usertaskwithresult:
  # single|multiple
  modeExecution: singlezeebe
  pleaseLogWorker: false
  doubleCheck: true
  useTaskAPI: true


# Configuration for running connectors in bundle with connector-runtime

# local connection
camunda:
 client:
     mode: selfManaged
     zeebe:
       enabled: true
       grpc-address: http://localhost:26500
       rest-address: http://localhost:8080
       preferRestOverGrpc: false





# Don't run the connection to Operate (not an inbound connection)
camunda.connector.polling.enabled: false
camunda.connector.webhook.enabled: false
spring.main.web-application-type: none
operate.client.enabled: false

tasklist:
  url:
  username: demo
  userpassword: demo
  clientId:
  clientSecret:
  taskListKeycloakUrl:

